apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.herald.service.type }}
  ports:
    - port: {{ .Values.herald.service.port }}
      {{- if .Values.herald.service.nodePort }}
      nodePort: {{ .Values.herald.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: herald
    - port: {{ .Values.herald.debug.port }}
      {{- if .Values.herald.debug.nodePort }}
      nodePort: {{ .Values.herald.debug.nodePort }}
      {{- end }}
      protocol: TCP
      name: herald-debug