apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: emqx-config
data:
  EMQX_NAME: emqx
  EMQX_CLUSTER__DISCOVERY: k8s
  EMQX_CLUSTER__K8S__APP_NAME: emqx
  EMQX_CLUSTER__K8S__SERVICE_NAME: {{ include "herald.fullname" . }}
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__APISERVER: {{ .Values.emqx.k8sApiServer }}
  EMQX_CLUSTER__K8S__SUFFIX: {{ .Values.emqx.k8sSuffix }}
  EMQX_CLUSTER__K8S__NAMESPACE: {{ .Release.Namespace }}
