apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: emqx-statefulset
  labels:
    app: emqx
spec:
  replicas: 3
  serviceName: emqx-headless
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      serviceAccountName: emqx
      containers:
        - name: emqx
          image: emqx/emqx:4.3.7
          ports:
            - name: mqtt
              containerPort: 1883
            #- name: mqttssl
            #  containerPort: 8883
            #- name: mgmt
            #  containerPort: 8081
            #- name: ws
            #  containerPort: 8083
            #- name: wss
            #  containerPort: 8084
            #- name: dashboard
            #  containerPort: 18083
          envFrom:
            - configMapRef:
                name: emqx-config
          volumeMounts:
            - name: emqx-pvc
              mountPath: "/opt/emqx/data/mnesia"
  volumeClaimTemplates:
    - metadata:
        name: emqx-pvc
        #annotations:
        #  volume.alpha.kubernetes.io/storage-class: manual
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
