apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: echo
build:
  artifacts:
  - image: elio
  local: {}
    #docker:
    #  dockerfile: Dockerfile
deploy:
  statusCheckDeadlineSeconds: 540
  kubectl:
    manifests:
    - deployment.yaml
