apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: echo
build:
  artifacts:
  - image: elio-echo
    docker:
      dockerfile: app/echo/assets.k8s/Dockerfile
    #sync:
    #  manual:
    #  - src: '../echo.go'
    #    dest: static
portForward:
- resourceType: deployment
  resourceName: elio-echo
  port: 30001
  localPort: 7001
- resourceType: deployment
  resourceName: elio-echo
  port: 30002
  localPort: 56268
profiles:
- name: dev
  deploy:
    kubectl:
      manifests:
        - app/echo/assets.k8s/profiles/dev.yaml
- name: debug
  deploy:
    kubectl:
      manifests:
        - app/echo/assets.k8s/profiles/debug.yaml
