apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold-herald
build:
  local:
    push: true
  tagPolicy:
    sha256: {}
  artifacts:
    - image: localhost:5001/skaffold-herald
      docker:
        dockerfile: ./app/herald/assets.k8s/Dockerfile
deploy:
  helm:
    releases: 
    - name: skaffold-herald
      chartPath: ./app/herald/assets.k8s/helm
      skipBuildDependencies: true
      valuesFiles:
        - ./app/herald/assets.k8s/helm/values.yaml
      setValues:
        herald:
          image: localhost:5001/skaffold-herald
      imageStrategy:
        helm: {}
portForward:
  - resourceType: deployment
    resourceName: skaffold-herald
    port: 30003
    localPort: 7003
  - resourceType: deployment
    resourceName: skaffold-herald
    port: 30004
    localPort: 56268
