apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold-herald
build:
  local:
    push: true
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: localhost:5001/skaffold-herald
      docker:
        dockerfile: app/herald/assets.k8s/Dockerfile
deploy:
  helm:
    releases:
    - name: skaffold-herald
      chartPath: app/herald/assets.k8s/helm
      skipBuildDependencies: true
      valuesFiles:
        - app/herald/assets.k8s/helm/values.yaml
      setValues:
        herald:
          image: localhost:5001/skaffold-herald
      imageStrategy:
        helm: {}

#portForward:
#  - resourceType: deployment
#    resourceName: skaffold-herald
#    port: 7002
#    localPort: 7002
