apiVersion: v1
kind: Service
metadata:
 name: elio-echo
 labels:
   app: elio-echo
spec:
 ports:
  - port: 7001
    name: echo
    protocol: TCP
  - port: 56268
    name: echo-debug
    protocol: TCP
 clusterIP: None
 selector:
   app: elio-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: elio-echo
 labels:
   app: elio-echo
spec:
 replicas: 1
 selector:
   matchLabels:
     app: elio-echo
 template:
   metadata:
     labels:
       app: elio-echo
   spec:
     containers:
     - name: elio-echo
       image: elio-echo
