apiVersion: v1
kind: Service
metadata:
  name: herald-service
  labels:
    app: herald
spec:
  ports:
    - port: 7000
      protocol: TCP
  clusterIP: None
  selector:
    app: herald
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: herald-deployment
  labels:
    app: herald
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herald
  template:
    metadata:
      labels:
        app: herald
    spec:
      containers:
        - name: herald
          image: herald-image
