apiVersion: v1
kind: Namespace
metadata:
  name: herald
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: herald
  name: emqx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: herald
  name: emqx
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: herald
  name: emqx
roleRef:
  kind: ClusterRole
  name: emqx
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: herald
    name: emqx
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: herald
  name: emqx-config
data:
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  namespace: herald
  name: emqx-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  #- name: mqttssl
  #  port: 8883
  #  protocol: TCP
  #  targetPort: 8883
  #- name: mgmt
  #  port: 8081
  #  protocol: TCP
  #  targetPort: 8081
  #- name: websocket
  #  port: 8083
  #  protocol: TCP
  #  targetPort: 8083
  #- name: wss
  #  port: 8084
  #  protocol: TCP
  #  targetPort: 8084
  #- name: dashboard
  #  port: 18083
  #  protocol: TCP
  #  targetPort: 18083
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: herald
  name: emqx-statefulset
  labels:
    app: emqx
spec:
  replicas: 3
  serviceName: emqx-headless
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      namespace: herald
      labels:
        app: emqx
    spec:
      volumes:
      - name: emqx-data
        persistentVolumeClaim:
          claimName: emqx-pvc
      serviceAccountName: emqx
      containers:
      - name: emqx
        image: emqx/emqx:v4.1-rc.1
        ports:
        - name: mqtt
          containerPort: 1883
        #- name: mqttssl
        #  containerPort: 8883
        #- name: mgmt
        #  containerPort: 8081
        #- name: ws
        #  containerPort: 8083
        #- name: wss
        #  containerPort: 8084
        #- name: dashboard
        #  containerPort: 18083
        envFrom:
          - configMapRef:
              name: emqx-config
        volumeMounts:
        - name: emqx-data
          mountPath: "/opt/emqx/data/mnesia"
  volumeClaimTemplates:
  - metadata:
      name: emqx-pvc
      annotations:
        volume.alpha.kubernetes.io/storage-class: manual
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi