build:
  local:
    push: true
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: herald-image
      docker:
        dockerfile: app/herald/k8s-resources/Dockerfile
deploy:
  helm:
    releases:
      - name: herald
        skipBuildDependencies: true
        chartPath: app/herald/k8s-resources/helm
        valuesFiles:
          - app/herald/k8s-resources/helm/values.yaml
