apiVersion: v1
kind: Namespace
metadata:
  name: herald
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: herald
  name: emqx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: herald
  name: emqx
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: herald
  name: emqx
roleRef:
  kind: ClusterRole
  name: emqx
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: herald
    name: emqx
---
apiVersion: v1
kind: Service
metadata:
  namespace: herald
  name: herald-service
  labels:
    app: herald
spec:
  ports:
    - port: 7000
      protocol: TCP
  clusterIP: None
  selector:
    app: herald
---
apiVersion: v1
kind: Service
metadata:
  namespace: herald
  name: emqx-service
  labels:
    app: emqx
spec:
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
    #- name: mqttssl
    #  port: 8883
    #  protocol: TCP
    #  targetPort: mqttssl
    #- name: mgmt
    #  port: 8081
    #  protocol: TCP
    #  targetPort: mgmt
    #- name: ws
    #  port: 8083
    #  protocol: TCP
    #  targetPort: ws
    #- name: wss
    #  port: 8084
    #  protocol: TCP
    #  targetPort: wss
    #- name: dashboard
    #  port: 18083
    #  protocol: TCP
    #  targetPort: dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: herald
  name: herald-deployment
  labels:
    app: herald
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herald
  template:
    metadata:
      labels:
        app: herald
    spec:
      containers:
        - name: herald
          image: herald-image
          env:
            - name: HERALD_IN_URL
              value: 0.0.0.0:7000
            - name: HERALD_MQTT_URL
              value: emqx-service:1883
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: herald
  name: emqx-deployment
  labels:
    app: emqx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      serviceAccountName: emqx
      containers:
      - name: emqx
        image: emqx/emqx:4.3.7
        ports:
        - name: mqtt
          containerPort: 1883
        #- name: mqttssl
        #  containerPort: 8883
        #- name: mgmt
        #  containerPort: 8081
        #- name: ws
        #  containerPort: 8083
        #- name: wss
        #  containerPort: 8084
        #- name: dashboard
        #  containerPort: 18083
