# kind.cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 7001
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30002
        hostPort: 56267
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30003
        hostPort: 7003
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30004
        hostPort: 56268
        listenAddress: "0.0.0.0"
        protocol: tcp
  - role: worker
